train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: 'map/map_train_HR'
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 56
      scale_max: 2
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: 'map/val'
      first_k: 60
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 56
      scale_max: 2
  batch_size: 32

data_norm:
#  inp: {sub: [0.5], div: [0.5]}
#  gt: {sub: [0.5], div: [0.5]}

model:
#  name: edsr-baseline
  name: swinsrv3
  args:
    scale: 2
  sd: save/_swinsrv3_x2_train3/epoch-last.pth

optimizer:
  name: adam
  args:
    lr: 6.e-5
epoch_max: 1000
multi_step_lr:
#  milestones: [200, 400, 600, 800]
#  gamma: 0.5

epoch_val: 1
epoch_save: 200
